version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Install enviroments complete"

  pre_build:
    commands:
      - CurrentVersion=$(echo $(aws lambda get-alias --function-name lambda --name dev --region ap-southeast-1 | grep FunctionVersion | tail -1 |tr -cd "[0-9]"))
      - echo "Pre build complete"

  build:
    commands:
      - echo "Building the Spring Boot application with Maven"
      - chmod +x ./mvnw
      - ./mvnw clean install
      - echo "Build complete"

  post_build:
    commands:
      - echo $CurrentVersion
      - echo $TargetVersion
      - sed -e 's/{{CurrentVersion}}/'$CurrentVersion'/g' -e 's/{{TargetVersion}}/'$TargetVersion'/g' appspec.yaml > appspec.yaml
      - echo "Post build complete"

artifacts:
  files:
    - target/lambda-0.0.1-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
