version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      echo "Prepare enviroments"

  pre_build:
    commands:
      echo "Starting pre_build phase"

  build:
    commands:
      echo "Building the Spring Boot application with Maven"
      ./mvnw clean install

  post_build:
    commands:
      echo "Build complete"

artifacts:
  files:
    - target/lambda-0.0.1-SNAPSHOT.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
